// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoDvUzqWe8lfBEAlXyHkERfOjgvPhuEw4',
    appId: '1:147460607214:web:7afa8c4e6e842cf674b7ff',
    messagingSenderId: '147460607214',
    projectId: 'crypto-wallet-b18f6',
    authDomain: 'crypto-wallet-b18f6.firebaseapp.com',
    storageBucket: 'crypto-wallet-b18f6.appspot.com',
    measurementId: 'G-Y21MK2DMEX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEo1sDBjVjjtklD5LwbFneBqDKJIuSPYI',
    appId: '1:147460607214:android:b0ee5ff2c6f1325174b7ff',
    messagingSenderId: '147460607214',
    projectId: 'crypto-wallet-b18f6',
    storageBucket: 'crypto-wallet-b18f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvGCFgpQehT13PBanCTfSm73zUvXwpEOk',
    appId: '1:147460607214:ios:4b61142582ea80af74b7ff',
    messagingSenderId: '147460607214',
    projectId: 'crypto-wallet-b18f6',
    storageBucket: 'crypto-wallet-b18f6.appspot.com',
    iosClientId:
        '147460607214-tm46ie693a6t27m1d6loqqvtn8rms26i.apps.googleusercontent.com',
    iosBundleId: 'com.bynarr.nursing-home',
  );
}
